/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	Ilsav1 "github.com/jungmin17/ilsa-clientset-example/pkg/apis/Ilsa/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMyPods implements MyPodInterface
type FakeMyPods struct {
	Fake *FakeIlsaV1
	ns   string
}

var mypodsResource = schema.GroupVersionResource{Group: "ilsa.example.com", Version: "v1", Resource: "mypods"}

var mypodsKind = schema.GroupVersionKind{Group: "ilsa.example.com", Version: "v1", Kind: "MyPod"}

// Get takes name of the myPod, and returns the corresponding myPod object, and an error if there is any.
func (c *FakeMyPods) Get(ctx context.Context, name string, options v1.GetOptions) (result *Ilsav1.MyPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mypodsResource, c.ns, name), &Ilsav1.MyPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*Ilsav1.MyPod), err
}

// List takes label and field selectors, and returns the list of MyPods that match those selectors.
func (c *FakeMyPods) List(ctx context.Context, opts v1.ListOptions) (result *Ilsav1.MyPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mypodsResource, mypodsKind, c.ns, opts), &Ilsav1.MyPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &Ilsav1.MyPodList{ListMeta: obj.(*Ilsav1.MyPodList).ListMeta}
	for _, item := range obj.(*Ilsav1.MyPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested myPods.
func (c *FakeMyPods) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mypodsResource, c.ns, opts))

}

// Create takes the representation of a myPod and creates it.  Returns the server's representation of the myPod, and an error, if there is any.
func (c *FakeMyPods) Create(ctx context.Context, myPod *Ilsav1.MyPod, opts v1.CreateOptions) (result *Ilsav1.MyPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mypodsResource, c.ns, myPod), &Ilsav1.MyPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*Ilsav1.MyPod), err
}

// Update takes the representation of a myPod and updates it. Returns the server's representation of the myPod, and an error, if there is any.
func (c *FakeMyPods) Update(ctx context.Context, myPod *Ilsav1.MyPod, opts v1.UpdateOptions) (result *Ilsav1.MyPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mypodsResource, c.ns, myPod), &Ilsav1.MyPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*Ilsav1.MyPod), err
}

// Delete takes name of the myPod and deletes it. Returns an error if one occurs.
func (c *FakeMyPods) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mypodsResource, c.ns, name), &Ilsav1.MyPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMyPods) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mypodsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &Ilsav1.MyPodList{})
	return err
}

// Patch applies the patch and returns the patched myPod.
func (c *FakeMyPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *Ilsav1.MyPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mypodsResource, c.ns, name, pt, data, subresources...), &Ilsav1.MyPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*Ilsav1.MyPod), err
}
