/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/jungmin17/ilsa-clientset-example/pkg/apis/Ilsa/v1"
	scheme "github.com/jungmin17/ilsa-clientset-example/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MyPodsGetter has a method to return a MyPodInterface.
// A group's client should implement this interface.
type MyPodsGetter interface {
	MyPods(namespace string) MyPodInterface
}

// MyPodInterface has methods to work with MyPod resources.
type MyPodInterface interface {
	Create(ctx context.Context, myPod *v1.MyPod, opts metav1.CreateOptions) (*v1.MyPod, error)
	Update(ctx context.Context, myPod *v1.MyPod, opts metav1.UpdateOptions) (*v1.MyPod, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MyPod, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MyPodList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MyPod, err error)
	MyPodExpansion
}

// myPods implements MyPodInterface
type myPods struct {
	client rest.Interface
	ns     string
}

// newMyPods returns a MyPods
func newMyPods(c *IlsaV1Client, namespace string) *myPods {
	return &myPods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the myPod, and returns the corresponding myPod object, and an error if there is any.
func (c *myPods) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MyPod, err error) {
	result = &v1.MyPod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mypods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MyPods that match those selectors.
func (c *myPods) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MyPodList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MyPodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mypods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested myPods.
func (c *myPods) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mypods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a myPod and creates it.  Returns the server's representation of the myPod, and an error, if there is any.
func (c *myPods) Create(ctx context.Context, myPod *v1.MyPod, opts metav1.CreateOptions) (result *v1.MyPod, err error) {
	result = &v1.MyPod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mypods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myPod).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a myPod and updates it. Returns the server's representation of the myPod, and an error, if there is any.
func (c *myPods) Update(ctx context.Context, myPod *v1.MyPod, opts metav1.UpdateOptions) (result *v1.MyPod, err error) {
	result = &v1.MyPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mypods").
		Name(myPod.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myPod).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the myPod and deletes it. Returns an error if one occurs.
func (c *myPods) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mypods").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *myPods) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mypods").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched myPod.
func (c *myPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MyPod, err error) {
	result = &v1.MyPod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mypods").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
